TestRazor/TestRazor/Controllers/ClienteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TestRazor.Common;
using TestRazor.ExtensionsClasses;
using TestRazor.Models;
using TestRazor.ViewModel;

namespace TestRazor.Controllers
{
    public class ClienteController : Controller
    {
        GestorClientes gestor = new GestorClientes();
        // GET: Cliente
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Alta()
        {
            return View();
        }
        public ActionResult Guardar(Clientes clienteViewModel)
        {
           
            if (ModelState.IsValid)
            {
                gestor.Guardar(clienteViewModel.ConvertirAModelo());
            }
            else
            {
                return View("Alta");
            }
            return RedirectToAction("Listar");
        }

        public ActionResult Listar()
        {
            var clientes = gestor.Listar();

           
            return View(clientes.ConvertirAViewModel());
        }

        public ActionResult Buscar()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Busqueda(string cliente)
        {
            Logger.Log("Pasó por el action busqueda");
            var clientes = gestor.Buscar(cliente);
            return View(clientes.ConvertirAViewModel());
        }

        public ActionResult EliminarPorId(int id)
        {
            gestor.Eliminar(id);
            return RedirectToAction("Listar");
        }

        public ActionResult EliminarPorApellidoyNombre(string apellido, string nombre)
        {
            gestor.Eliminar(apellido, nombre);
            return RedirectToAction("Listar");
        }
    }
}

TestRazor/TestRazor/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TestRazor.Models;
using TestRazor.ViewModel;

namespace TestRazor.Controllers
{
    public class HomeController : Controller
    {
        GestorClientes gestor = new GestorClientes();
        // GET: Home
        public ActionResult Index()
        {
            //var gestor = new GestorVentas();
            //var listaProductos = gestor.ObtenerProductos();
            //var listaClientes = gestor.ObtenerClientes();

            //var venta = new Venta();
            //venta.Clientes = listaClientes;
            //venta.Productos = listaProductos;
            return View();
        }

        public ActionResult Formulario()
        {
            return View();
        }

        public ActionResult FormularioProducto()
        {
            return View();
        }

        public ActionResult FormularioProveedor()
        {
            return View();
        }


    }




}

TestRazor/TestRazor/Controllers/ProductoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TestRazor.Models;
using TestRazor.ViewModel;

namespace TestRazor.Controllers
{
    public class ProductoController : Controller
    {
        GestorProductos gestor = new GestorProductos();
        // GET: Producto
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Guardar(Productos producto)
        {
            if (ModelState.IsValid)
            {
                gestor.Guardar(producto);
            }
            else
            {
                return View("FormularioProducto");
            }
            return View("Index");
        }
    }
    }

TestRazor/TestRazor/Controllers/ProveedorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TestRazor.Models;


namespace TestRazor.Controllers
{
    public class ProveedorController : Controller
    {
        GestorProveedor gestor = new GestorProveedor();
        // GET: Proveedor
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Guardar(ViewModel.Proveedor proveedor)
        {
            var proveedorModel = new Models.Proveedor();
            proveedorModel.Nombre = proveedor.Nombre;
            proveedorModel.Telefono = proveedor.Telefono;
            if (ModelState.IsValid)
            {
                gestor.Guardar(proveedorModel);
            }
            else
            {
                return View("FormularioProveedor");
            }
            return View("Home/Index");
        }
    }
    }

TestRazor/TestRazor/Views/Home/Formulario.cshtml
@model TestRazor.ViewModel.Clientes

@{
    ViewBag.Title = "Formulario";
}

<h2>Ingresa tus datos</h2>
<br />
@*<form action=@Url.Action("Guardar","Home") method="POST">
    Nombre: <input type="text" name="Nombre" /><br /><br />
    Apellido: <input type="text" name="Apellido" /><br /><br/>
    <input type="submit" value="Submit" /> <input type="reset" value="Reset" />
</form>*@

@using (Html.BeginForm("Guardar", "Cliente"))
{
    @Html.ValidationSummary()
    @Html.EditorForModel()
    <input type="submit" />
}

TestRazor/TestRazor/Views/Home/FormularioProducto.cshtml
@model TestRazor.ViewModel.Productos
@{
    ViewBag.Title = "FormularioProducto";
}

<h2>FormularioProducto</h2>

@using (Html.BeginForm("Guardar", "Producto"))
{
    @Html.ValidationSummary()
    @Html.EditorForModel()
    <input type="submit" />
}

TestRazor/TestRazor/Views/Home/FormularioProveedor.cshtml
@model TestRazor.ViewModel.Proveedor
@{
    ViewBag.Title = "FormularioProveedor";
}

<h2>FormularioProveedor</h2>

@using (Html.BeginForm("Guardar", "Proveedor"))
{
    @Html.ValidationSummary()
    @Html.EditorForModel()
    <input type="submit" />
}

TestRazor/TestRazor/Views/Home/Guardar.cshtml
@{
    ViewBag.Title = "Guardar";
}

<h2 style="color: #14C8EC">PERFECTO!!</h2>
<br />

<p>Tus datos son: @ViewBag.Apellido, @ViewBag.Nombre</p>

TestRazor/TestRazor/Views/Home/Index.cshtml
@using TestRazor.Models
@Model Cliente 



@{
    ViewBag.Title = "Principal";
}

<h2>Para completar el formulario de cliente <a href="../Home/Formulario">click aqui</a> </h2>

<h2>Para completar el formulario de producto <a href="../Home/FormularioProducto">click aqui</a> </h2>

TestRazor/TestRazor/Views/Home/Ventas.cshtml
@model TestRazor.ViewModel.Venta

@{
    ViewBag.Title = "Ventas";
}

<h2>Ventas</h2>

@for (int i = 0; i < Model.Clientes.Count; i++)
{
    <p>Cliente numero @i: @Model.Clientes[i].Apellido, @Model.Clientes[i].Nombre</p>
}

    